In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
df=files.upload()

Saving archive (7).zip to archive (7).zip

In [3]:
df.keys()

dict_keys(['archive (7).zip'])

In [4]:
import zipfile

with zipfile.ZipFile('archive (7).zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

In [5]:
import os
os.listdir()

['.config',
 'olist_products_dataset.csv',
 'product_category_name_translation.csv',
 'olist_geolocation_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_orders_dataset.csv',
 'archive (7).zip',
 'olist_customers_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_sellers_dataset.csv',
 'sample_data']

In [6]:
customers=pd.read_csv('olist_customers_dataset.csv')
geolocation=pd.read_csv('olist_geolocation_dataset.csv')
orders=pd.read_csv('olist_orders_dataset.csv')
order_items=pd.read_csv('olist_order_items_dataset.csv')
orders_reviews=pd.read_csv('olist_order_reviews_dataset.csv')
orders_payments=pd.read_csv('olist_order_payments_dataset.csv')
products=pd.read_csv('olist_products_dataset.csv')
sellers=pd.read_csv('olist_sellers_dataset.csv')
product_category=pd.read_csv('product_category_name_translation.csv')

In [7]:
orders.shape

(99441, 8)

In [8]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [9]:
orders.duplicated().sum()

np.int64(0)

In [10]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
orders.loc[orders["order_delivered_customer_date"].isnull(),
           "order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [12]:
orders.loc[orders["order_delivered_carrier_date"].isnull(),
           "order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [13]:
orders.loc[
    orders["order_delivered_carrier_date"].isnull(),
    "order_status"
].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [14]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [15]:
customers.duplicated().sum()

np.int64(0)

In [16]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [17]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [18]:
order_items.duplicated().sum()

np.int64(0)

In [19]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [20]:
orders_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [21]:
orders_payments.duplicated().sum()

np.int64(0)

In [22]:
orders_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [23]:
product_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [24]:
products.duplicated().sum()

np.int64(0)

In [25]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [26]:
products["product_category_name"] = products["product_category_name"].fillna("Unknown")

In [27]:
products["product_weight_g"] = products["product_weight_g"].fillna(products["product_weight_g"].median())

In [28]:
products["product_length_cm"] = products["product_length_cm"].fillna(products["product_length_cm"].median())

products["product_height_cm"] = products["product_height_cm"].fillna(products["product_height_cm"].median())

products["product_width_cm"] = products["product_width_cm"].fillna(products["product_width_cm"].median())

products["product_name_lenght"] = products["product_name_lenght"].fillna(products["product_name_lenght"].mean())

In [29]:
products["product_description_lenght"] = products["product_description_lenght"].fillna(
products["product_description_lenght"].median())

products["product_photos_qty"] = products["product_photos_qty"].fillna(products["product_photos_qty"].median())

In [30]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [31]:
df=orders.merge(customers,on="customer_id",how="left")
print(df.shape)

(99441, 12)

In [32]:
df=df.merge(orders_payments,on="order_id",how="left")
print(df.shape)

(103887, 16)

In [33]:
df=df.merge(order_items,on="order_id",how="left")
print(df.shape)

(118434, 22)

In [34]:
df=df.merge(products,on="product_id",how="left")
print(df.shape)

(118434, 30)

In [35]:
df=df.merge(orders_reviews,on="order_id",how="left")
print(df.shape)

(119143, 36)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  payment_sequential             119140 non-null  float64
 13  payment_type                   119140 non-null  object
 14  payment_installments           119140 non-null  float64
 15  payment_value                  119140 non-null  float64
 16  order_item_id                  118310 non-null  float64
 17  product_id                     118310 non-null  object
 18  seller_id                      118310 non-null  object
 19  shipping_limit_date            118310 non-null  object
 20  price                          118310 non-null  float64
 21  freight_value                  118310 non-null  float64
 22  product_category_name          118310 non-null  object
 23  product_name_lenght            118310 non-null  float64
 24  product_description_lenght     118310 non-null  float64
 25  product_photos_qty             118310 non-null  float64
 26  product_weight_g               118310 non-null  float64
 27  product_length_cm              118310 non-null  float64
 28  product_height_cm              118310 non-null  float64
 29  product_width_cm               118310 non-null  float64
 30  review_id                      118146 non-null  object
 31  review_score                   118146 non-null  float64
 32  review_comment_title           13989 non-null   object
 33  review_comment_message         50245 non-null   object
 34  review_creation_date           118146 non-null  object
 35  review_answer_timestamp        118146 non-null  object
dtypes: float64(14), int64(1), object(21)
memory usage: 32.7+ MB

In [37]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,400.0,19.0,13.0,19.0,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,420.0,24.0,19.0,21.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58

In [38]:
df.shape

(119143, 36)

In [39]:
df["order_delivered_customer_date"] = pd.to_datetime(df["order_delivered_customer_date"])
df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
df["delivery_days"]=(df["order_delivered_customer_date"]-df["order_purchase_timestamp"]).dt.days
print(df["delivery_days"])

0          8.0
1          8.0
2          8.0
3         13.0
4          9.0
          ...
119138    22.0
119139    24.0
119140    17.0
119141    17.0
119142     7.0
Name: delivery_days, Length: 119143, dtype: float64

In [40]:
df["order_estimated_delivery_date"] = pd.to_datetime(df["order_estimated_delivery_date"])
df["delay_days"] = (df["order_delivered_customer_date"]- df["order_estimated_delivery_date"]).dt.days
print(df["delay_days"])

0         -8.0
1         -8.0
2         -8.0
3         -6.0
4        -18.0
          ...
119138    -2.0
119139    -6.0
119140   -21.0
119141   -21.0
119142   -18.0
Name: delay_days, Length: 119143, dtype: float64

1.**Total_revenue**

In [41]:
total_revenue = df["payment_value"].sum()
total_revenue

np.float64(20579664.01)

2.**Order Status Distribution**

In [42]:
total_order_value = df["order_status"].value_counts()
total_order_value

order_status
delivered      115723
shipped          1256
canceled          750
unavailable       652
invoiced          378
processing        376
created             5
approved            3
Name: count, dtype: int64

In [43]:
df['order_status'].value_counts(normalize=True)*100

order_status
delivered      97.129500
shipped         1.054195
canceled        0.629496
unavailable     0.547242
invoiced        0.317266
processing      0.315587
created         0.004197
approved        0.002518
Name: proportion, dtype: float64

In [44]:
total_orders = len(df)
canceled_orders = len(df[df["order_status"]== "canceled"])
canceled_orders_percentage = (canceled_orders/total_orders)*100
canceled_orders_percentage

0.6294956480867528

In [45]:
delivered_orders = len(df[df["order_status"]=="delivered"])
delivered_orders_percentage = (delivered_orders/total_orders)*100
delivered_orders_percentage

97.1294998447244

**3. revenue lost due to cancellations**

In [46]:
df[df["order_status"]== "canceled"]["payment_value"].sum()

np.float64(188072.16)

**4.top 10 products by revenue**

In [47]:
df.groupby("product_category_name")["payment_value"].sum().sort_values(ascending=False).head(10)

product_category_name
cama_mesa_banho           1743998.80
beleza_saude              1662963.59
informatica_acessorios    1599481.06
moveis_decoracao          1443963.61
relogios_presentes        1430553.48
esporte_lazer             1400223.07
utilidades_domesticas     1097900.09
automotivo                 855095.68
ferramentas_jardim         840721.59
cool_stuff                 781933.97
Name: payment_value, dtype: float64

**5.average delivery time**

In [48]:
df['is_delayed'] = (df['delay_days'] > 0).astype(int)
df["is_delayed"].mean()*100

np.float64(6.344476805183687)

**6. review score vs revenue**

In [49]:
df.groupby("review_score")["payment_value"].mean()

review_score
1.0    231.630629
2.0    191.316970
3.0    167.840188
4.0    163.469189
5.0    160.777450
Name: payment_value, dtype: float64

**7. revenue by state**

In [50]:
df.groupby("customer_state")["payment_value"].sum().sort_values(ascending=False)

customer_state
SP    7726078.35
RJ    2795615.67
MG    2351221.09
RS    1160175.66
PR    1079795.49
BA     805070.98
SC     801276.45
GO     520481.65
DF     438095.32
ES     408611.64
PE     380294.18
CE     349290.36
PA     263217.70
MT     257802.26
MA     200363.24
PB     181660.73
MS     167670.27
PI     137158.89
RN     117192.91
AL     112296.47
SE      90651.44
TO      72412.08
RO      69184.48
AM      34956.93
AC      24984.86
AP      21642.70
RR      12462.21
Name: payment_value, dtype: float64

In [51]:
from google.colab import files
orders.to_csv("orders_cleaned.csv", index=False)
files.download("orders_cleaned.csv")

In [52]:
customers.to_csv("customers_cleaned.csv", index=False)
files.download("customers_cleaned.csv")

In [53]:
order_items.to_csv("order_items_cleaned.csv", index=False)
files.download("order_items_cleaned.csv")

In [54]:
orders_payments.to_csv("payments_cleaned.csv", index=False)
files.download("payments_cleaned.csv")

In [55]:
orders_reviews.to_csv("reviews_cleaned.csv", index=False)
files.download("reviews_cleaned.csv")